version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-rsm
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - my_resume_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-rsm
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - my_resume_network
    depends_on:
      - mongo

  my-resume-api:
    image: my-resume-backend:latest
    container_name: my-resume-api
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_resume_network
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: root

  my-resume-ui:
    image: my-resume-frontend:latest
    container_name: my-resume-ui
    restart: always
    ports:
      - "4200:80"
    networks:
      - my_resume_network
    depends_on:
      - my-resume-api

networks:
  my_resume_network:
    driver: bridge
