spring:
  application:
    name: my-resume-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: resume_db
      username: root
      password: root
      authentication-database: admin
  ai:
    openai:
      api-key:  ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL}
          temperature: ${OPENAI_CHAT_TEMPERATURE}
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
#            client-: ${GOOGLE_OAUTH_CLIENT_SECRET}
#        provider:
#          google:
#            user-name-attribute: ${GOOGLE_USER_NAME_ATTRIBUTE}
server:
  port: 8088
  servlet:
    context-path: /api/v1/







